### ISSUE TITLE
no preview window and SigFalt

### ISSUE THREAD

**Issue by thanosdr** [BitCurator/bitcurator-redact-pdf#2]
running even the sample pdf and example produces no preview window. When clicking the pdf name in the left bar (to try and start redaction) the program throws an error and crashes.

happy to provide more info as needed. This looks like a killer tool if it ever works again.

**Comment by kamwoods** [comment]
Development on this research tool ended in 2018. It is effectively defunct as it no longer has an active maintainer.

**Comment by kamwoods** [comment]
Closing as this repository is now end-of-life.
